# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FirstScreen(object):
    def setupUi(self, FirstScreen):
        FirstScreen.setObjectName("FirstScreen")
        FirstScreen.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(FirstScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.gridGroupBox.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gridGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gridGroupBox)
        self.label.setStyleSheet("font: 32pt \"Old English Text MT\";\n"
"background-color: rgb(7, 255, 255);\n"
"background-color: rgb(21, 5, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"color:white")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Manual = QtWidgets.QPushButton(self.gridGroupBox)
        self.Manual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Manual.setStyleSheet("color:white;\n"
"background-color: rgb(0, 0, 127);")
        self.Manual.setObjectName("Manual")
        self.horizontalLayout_3.addWidget(self.Manual)
        self.Auto = QtWidgets.QPushButton(self.gridGroupBox)
        self.Auto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Auto.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color:rgb(255, 255, 255)")
        self.Auto.setObjectName("Auto")
        self.horizontalLayout_3.addWidget(self.Auto)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_2.setStyleSheet("background-color: white\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../OneDrive/Pictures/Screenshot 2023-08-29 172316 (2).png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.gridGroupBox)
        FirstScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FirstScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        FirstScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FirstScreen)
        self.statusbar.setObjectName("statusbar")
        FirstScreen.setStatusBar(self.statusbar)

        self.retranslateUi(FirstScreen)
        QtCore.QMetaObject.connectSlotsByName(FirstScreen)

    def retranslateUi(self, FirstScreen):
        _translate = QtCore.QCoreApplication.translate
        FirstScreen.setWindowTitle(_translate("FirstScreen", "MainWindow"))
        self.label.setText(_translate("FirstScreen", "Welcome back, and have a safe drive ;)"))
        self.Manual.setText(_translate("FirstScreen", "Manual"))
        self.Auto.setText(_translate("FirstScreen", "Autonomous"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FirstScreen = QtWidgets.QMainWindow()
    ui = Ui_FirstScreen()
    ui.setupUi(FirstScreen)
    FirstScreen.show()
    sys.exit(app.exec_())
